#!/usr/bin/env bash
set -eo pipefail
log(){ echo -e "[action] $*" >&2; }
die(){ log "$@"; exit 1; }

checkout="$1"
target="$2"
paths="$3"

[ -e "$target" ] || mkdir -p "$target"
[ -d "$target" ] || die "Target ($target) must be a directory"
target="$(readlink -f "$target")" # ensure target is absolute

trap '{
  RV=$?
  rm -rf "$checkout"
  echo "paths=${COPIED[*]}" >> "$GITHUB_OUTPUT"
  exit $RV
}' EXIT

cd "$checkout"
COPIED=()
IFS=":"; shopt -s globstar; for path in $paths; do
  for file in $path; do
    if [ -e "$file" ]; then
      mkdir -p "$target/$(dirname "$file")"
      cp -r "$file" "$target/$file"
      COPIED+=("$file")
    else
      log "skipping $file (does not exist in repository checkout)"
    fi
  done
done